# Numpy Tutorials

Numpy is a general purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working
with these arrays. It is the fundamental package for scientific computing with python.

# what is an array

An array is a data-structure that stores values of same data type. In python, this is the main difference between arrays and lists.While python lists can contain values corresponding to different data types,arrays is python can only contains values corresponding to same data type

In [1]:
## initally lets import numpy

import numpy as np

myList = [1,2,3,4,5]
arr=np.array(myList);

In [2]:
type(arr)

numpy.ndarray

In [3]:
print(arr)

[1 2 3 4 5]


In [5]:
#one dimensional array
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape


(5,)

In [23]:

## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
#3*5 = 15 dimensional should be same for reshape the array
arr.shape

(3, 5)

In [10]:
arr.reshape(5,2)

ValueError: cannot reshape array of size 15 into shape (5,2)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [13]:
arr.shape

(3, 5)

In [14]:
arr=arr.reshape(1,15)

In [15]:
arr.shape

(1, 15)

In [16]:
arr

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

# Indexing

In [17]:
arr

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [20]:
arr=np.array([1,2,3,4,6,7,8,9])

In [21]:
arr

array([1, 2, 3, 4, 6, 7, 8, 9])

In [22]:
arr[3]

4

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [26]:
arr[0:3,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [27]:
arr[0:3,0:1]

array([[1],
       [2],
       [9]])

In [28]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [29]:
arr[1:3,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [31]:
arr[1:3,2:4]

array([[4, 5],
       [6, 8]])

In [34]:
arr[:,]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [35]:
arr[1:2,:]

array([[2, 3, 4, 5, 6]])

In [36]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [37]:
arr=np.arange(0,10)

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr=np.arange(0,10,2)

In [40]:
arr

array([0, 2, 4, 6, 8])

In [41]:
arr

array([0, 2, 4, 6, 8])

In [42]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [43]:
arr


array([0, 2, 4, 6, 8])

In [44]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
## copy function and broadcasting
arr[3:]=100


In [46]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [47]:
arr1=arr
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [48]:
arr1[3:]=500

In [49]:
arr
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [50]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [51]:
arr[3:]=100

In [52]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [54]:
arr1=arr.copy()

In [55]:
arr1[3:] = 500

In [56]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [57]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [58]:
arr>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [59]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [60]:
arr/2

array([ 0. ,  0.5,  1. , 50. , 50. , 50. , 50. , 50. , 50. , 50. ])

In [61]:
arr1[arr1==500]

array([500, 500, 500, 500, 500, 500, 500])

# Create Array and Reshape

In [66]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
arrfinal = arr*arr1

In [68]:
arrfinal

array([    0,     1,     4, 50000, 50000, 50000, 50000, 50000, 50000,
       50000])

In [69]:
np.ones(4)

array([1., 1., 1., 1.])

In [71]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [73]:
np.random.rand(3,3)

array([[0.29345862, 0.71566191, 0.553754  ],
       [0.61234882, 0.0812038 , 0.85696018],
       [0.39381269, 0.06892034, 0.27209201]])

In [75]:
np.random.rand(4,4)

array([[0.92888877, 0.11485063, 0.96969251, 0.20252073],
       [0.00103709, 0.17987631, 0.73791025, 0.7034041 ],
       [0.5707041 , 0.19383234, 0.61551219, 0.866228  ],
       [0.11822967, 0.44486907, 0.28024944, 0.73254261]])

In [76]:
np.random.randint(0,100,13)

array([14, 33, 63, 93,  9, 70, 79, 90, 94, 28, 44, 34, 63])

In [79]:
np.random.random_sample((1,5))

array([[0.47296552, 0.06020751, 0.83037966, 0.9006733 , 0.66596898]])